spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: server-edu
          uri: lb://server-edu
          predicates:
            - Path=/eduservice/**
        - id: service-ucenter
          uri: lb://service-ucenter
          predicates:
            - Path=/educenter/**

    nacos:
      discovery:
        server-addr: localhost:8848
  application:
    name: gateway

server:
  port: 8222