#server:
#  port: 8001
#spring:
#  application:
#    name: server-edu
#  profiles:
#    active: dev
#  datasource:
#    url: jdbc:mysql://localhost:3306/guli_teach?serverTimezone=GMT%2B8
#    username: root
#    password: 1786291
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: GMT+8
#  cloud:
#    nacos:
#      discovery:
#        server-addr: localhost:8848
#  redis:
#    host: 192.168.73.137
#    port: 6379
#    timeout: 18000
#    database: 0
##开启熔断机制
#feign:
#  hystrix:
#    enabled: true
#
#
#
#mybatis-plus:
##  configuration:
##    # mybatis日志
##    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  #让系统知道mapper.xml的位置
#  mapper-locations: classpath:mapper/**/*.xml
##
###设置日志级别
##logging:
##  level: info