server:
  port: 8006

spring:
  profiles:
    active: dev
  application:
    name: service-ucenter
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli_teach?serverTimezone=GMT%2B8
    username: root
    password: 1786291

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  redis:
    host: 192.168.73.137
    port: 6379
    timeout: 18000
    database: 0

mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
